Repository freiheit-com/kuberpult, pull requests merged in 2023-12, with the labels that each got.

#1186 FIxed issue with the example URL for Bitbucket's manifestRepoUrl
  charts/kuberpult/values.yaml.tpl
Labels: minor

#1194 Remove redundant wait condition in integration tests
  Earthfile
Labels: patch

#1185 Add env Dropdown to Product Version Page
  services/frontend-service/src/ui/App/PageRoutes.tsx
  services/frontend-service/src/ui/Pages/Environments/EnvironmentsPage.tsx
  services/frontend-service/src/ui/Pages/ProductVersion/ProductVersionPage.tsx
  services/frontend-service/src/ui/components/EnvironmentCard/EnvironmentCard.test.tsx
  services/frontend-service/src/ui/components/EnvironmentCard/EnvironmentCard.tsx
  services/frontend-service/src/ui/components/ProductVersion/ProductVersion.scss
  services/frontend-service/src/ui/components/ProductVersion/ProductVersion.test.tsx
  services/frontend-service/src/ui/components/ProductVersion/ProductVersion.tsx
  services/frontend-service/src/ui/components/ProductVersion/__snapshots__/ProductVersion.test.tsx.snap
  services/frontend-service/src/ui/utils/Links.tsx
  services/frontend-service/src/ui/utils/store.tsx
Labels: minor

#1197 Require kuberpult AND argocd version to mark app as deployed
  services/rollout-service/pkg/service/broadcast.go
  services/rollout-service/pkg/service/broadcast_test.go
  services/rollout-service/pkg/service/service_test.go
  services/rollout-service/pkg/versions/versions.go
  services/rollout-service/pkg/versions/versions_test.go
Labels: minor

#1165 Update README.md Design Principle Deploy often
  README.md
Labels: patch

#1199 Fix return from endpoint GetProductSummary() for empty Summary
  services/cd-service/pkg/service/tags.go
  services/frontend-service/src/ui/utils/Links.tsx
Labels: minor

#1203 Release kuberpult 1.15.0
  CHANGELOG.md
Labels: exclude

#1204 Improve renovate settings
  renovate.json
  renovate.json5
Labels: patch

#1213 Move Disconnect to the go func
  services/cd-service/pkg/repository/repository.go
Labels: patch

#1234 chore(deps): update react monorepo
  services/frontend-service/package.json
  services/frontend-service/pnpm-lock.yaml
Labels: renovate

#1233 chore(deps): update dependency @babel/core to ^7.19.1
  services/frontend-service/package.json
  services/frontend-service/pnpm-lock.yaml
Labels: renovate

#1214 fix: Upgrade dependencies with Renovate in GitHub action
  .github/workflows/renovate.yml
  renovate.json5
Labels: patch

#1238 chore(deps): update dependency @types/react to v18.2.44
  services/frontend-service/package.json
  services/frontend-service/pnpm-lock.yaml
Labels: renovate

#1239 chore(deps): update dependency @types/react to v18.2.45
  services/frontend-service/package.json
  services/frontend-service/pnpm-lock.yaml
Labels: renovate

#1240 perf: Add a new simpler protocol for calculating versions in the rollout service
  pkg/api/api.proto
  services/cd-service/pkg/cmd/server.go
  services/cd-service/pkg/repository/repository.go
  services/cd-service/pkg/repository/time.go
  services/cd-service/pkg/repository/transformer_test.go
  services/cd-service/pkg/service/version.go
  services/cd-service/pkg/service/version_test.go
Labels: patch

#1230 ci: Create common Earthfile for go builds
  Earthfile
  infrastructure/docker/builder/Dockerfile
  infrastructure/earthly/go/Earthfile
  services/cd-service/Earthfile
  services/frontend-service/Earthfile
  services/rollout-service/Earthfile
Labels: patch

#1245 chore(deps): update dependency @types/react-dom to v18.2.18
  services/frontend-service/package.json
  services/frontend-service/pnpm-lock.yaml
Labels: renovate

#1246 feat: Add source commit id to new version protocol
  pkg/api/api.proto
  services/cd-service/pkg/service/version.go
  services/cd-service/pkg/service/version_test.go
Labels: minor

#1242 fix(chart): Add healthz endpoint to BackendConfig
  charts/kuberpult/templates/cd-service.yaml
  charts/kuberpult/templates/ingress.yaml
Labels: patch

#1235 fix(deps): update npm
  services/frontend-service/package.json
  services/frontend-service/pnpm-lock.yaml
Labels: renovate

#1249 fix: add v prefix to helm chart upload
  .github/workflows/release.yml
Labels: patch

#1251 fix: Return 404 when deleting non-existent lock via REST
  services/cd-service/pkg/grpc/errors.go
  services/cd-service/pkg/repository/transformer.go
  services/cd-service/pkg/repository/transformer_test.go
  services/cd-service/pkg/service/batch_test.go
  services/frontend-service/pkg/handler/grpc.go
  services/frontend-service/pkg/handler/rolloutstatus.go
Labels: patch

#1247 feat: Use new dedicated version protocol
  services/rollout-service/pkg/cmd/server.go
  services/rollout-service/pkg/service/service_test.go
  services/rollout-service/pkg/versions/versions.go
  services/rollout-service/pkg/versions/versions_test.go
Labels: minor

#1253 fix: tag service images on release
  .github/workflows/release.yml
  Makefile
  Makefile.variables
Labels: patch

#1254 fix: releases need a full checkout, so that git-describe is stable
  .github/workflows/release.yml
Labels: patch

#1255 fix: explicitly (re)-fetch tags for release
  .github/workflows/release.yml
Labels: patch

#1252 Add new dispatcher service that handles background errors
  services/rollout-service/pkg/cmd/server.go
  services/rollout-service/pkg/service/dispatcher.go
  services/rollout-service/pkg/service/dispatcher_test.go
  services/rollout-service/pkg/service/service.go
  services/rollout-service/pkg/service/service_test.go
Labels: minor

#1258 fix: service images are prefixed by kuberpult
  Makefile
  Makefile.variables
Labels: patch

#1260 fix: add missing author for new version endpoint
  services/rollout-service/pkg/versions/versions.go
  services/rollout-service/pkg/versions/versions_test.go
Labels: patch
