Repository freiheit-com/kuberpult, pull requests merged in 2023-11, with the labels that each got.

#1076 Integration test for frontend main page
  services/cd-service/Buildfile.yaml
  services/frontend-service/Buildfile.yaml
  services/rollout-service/Buildfile.yaml
  tests/integration-tests/release_test.go
Labels: patch

#1078 Fix missing ghcr.io image upload
  Makefile.variables
Labels: exclude

#1077 Send dora events to revolution
  charts/kuberpult/templates/rollout-service.yaml
  charts/kuberpult/values.yaml.tpl
  go.mod
  services/rollout-service/pkg/cmd/server.go
  services/rollout-service/pkg/revolution/revolution.go
  services/rollout-service/pkg/revolution/revolution_test.go
  services/rollout-service/pkg/service/broadcast.go
  services/rollout-service/pkg/versions/versions.go
  services/rollout-service/pkg/versions/versions_test.go
Labels: minor

#1079 Release 1.11.0
  CHANGELOG.md
Labels: exclude

#1080 Allow renovate to run at any time
  renovate.json
Labels: exclude

#1081 Fix: Add helm dependency to release pipeline
  charts/kuberpult/Makefile
Labels: exclude

#1082 Release 1.11.0
  services/frontend-service/Buildfile.yaml
Labels: exclude

#1093 Fix: set env vars in tests
  services/frontend-service/Makefile
  services/frontend-service/pkg/cmd/server_test.go
Labels: patch

#1075 Use earthly to build kuberpult locally
  Earthfile
  Makefile
  README_DEVELOPERS.md
  buf_sha256.txt
  codereviewr.yaml
  docker-compose-earthly.yml
  pkg/Earthfile
  services/cd-service/Earthfile
  services/frontend-service/Earthfile
Labels: exclude

#1094 Always add /metrics endpoint
  pkg/metrics/metrics.go
  pkg/setup/setup.go
  pkg/setup/setup_test.go
  services/rollout-service/pkg/cmd/server.go
Labels: patch

#1063 Add Initial Product Version Page
  services/frontend-service/src/assets/_variables.scss
  services/frontend-service/src/ui/App/PageRoutes.tsx
  services/frontend-service/src/ui/Pages/Environments/EnvironmentsPage.test.tsx
  services/frontend-service/src/ui/Pages/ProductVersion/ProductVersionPage.test.tsx
  services/frontend-service/src/ui/Pages/ProductVersion/ProductVersionPage.tsx
  services/frontend-service/src/ui/components/EnvironmentCard/EnvironmentCard.scss
  services/frontend-service/src/ui/components/EnvironmentCard/EnvironmentCard.test.tsx
  services/frontend-service/src/ui/components/EnvironmentCard/EnvironmentCard.tsx
  services/frontend-service/src/ui/components/ProductVersion/ProductVersion.scss
  services/frontend-service/src/ui/components/ProductVersion/ProductVersion.test.tsx
  services/frontend-service/src/ui/components/ProductVersion/ProductVersion.tsx
Labels: minor

#1103 tweak: use compose plugin of docker, should be available ~everywhere now
  Makefile
Labels: patch

#1102 SRX-57Q3B7: Remove codereviewr
  .github/workflows/code-reviewer-build.yml
  .github/workflows/code-reviewer-push.yml
  Makefile
  codereviewr.yaml
  infrastructure/scripts/make/analyze.sh
Labels: patch

#1101 SRX-FZ6M63/#1043: fix colors for environments
  pkg/api/api.proto
  services/cd-service/pkg/mapper/environments_config.go
  services/cd-service/pkg/mapper/environments_config_test.go
Labels: patch

#1104 UI: Fix typo Unkwown → Unknown
  services/frontend-service/src/ui/components/ReleaseCard/ReleaseCard.tsx
Labels: patch

#943 Add dedicated setup for health checking
  charts/kuberpult/templates/cd-service.yaml
  charts/kuberpult/templates/frontend-service.yaml
  charts/kuberpult/templates/rollout-service.yaml
  pkg/setup/health.go
  pkg/setup/setup.go
  pkg/setup/setup_test.go
  services/cd-service/pkg/cmd/server.go
  services/cd-service/pkg/repository/repository.go
  services/cd-service/pkg/repository/repository_test.go
  services/frontend-service/pkg/cmd/server.go
  services/frontend-service/pkg/cmd/server_test.go
  services/rollout-service/pkg/cmd/server.go
  services/rollout-service/pkg/service/service.go
  services/rollout-service/pkg/service/service_test.go
Labels: minor

#1110 Release 1.12.0
  CHANGELOG.md
  services/cd-service/Buildfile.yaml
  services/frontend-service/Buildfile.yaml
  services/rollout-service/Buildfile.yaml
Labels: exclude

#1117 Always build all services
  services/cd-service/Buildfile.yaml
  services/frontend-service/Buildfile.yaml
  services/rollout-service/Buildfile.yaml
Labels: patch

#1116 Change localhost to 127.0.0.1 in rollout-service tests
  services/rollout-service/pkg/cmd/server_test.go
Labels: exclude

#1109 Add a unified retry mechanism for background tasks
  pkg/setup/health.go
  services/rollout-service/pkg/cmd/server.go
  services/rollout-service/pkg/notifier/subscriber.go
  services/rollout-service/pkg/notifier/subscriber_test.go
  services/rollout-service/pkg/service/service.go
  services/rollout-service/pkg/service/service_test.go
  services/rollout-service/pkg/versions/versions.go
  services/rollout-service/pkg/versions/versions_test.go
Labels: minor

#1111 Remove IMAGE_REGISTRY definition in Makefile.variables
  Makefile.variables
Labels: exclude

#1112 Add filtering by team for the GetStatus endpoint
  pkg/api/api.proto
  services/rollout-service/pkg/service/broadcast.go
  services/rollout-service/pkg/service/broadcast_test.go
  services/rollout-service/pkg/versions/versions.go
  services/rollout-service/pkg/versions/versions_test.go
Labels: minor

#1105 Fix: empty dora token break rollout service deployment
  charts/kuberpult/templates/rollout-service.yaml
Labels: patch

#1120 Add filtering by team to the frontend-service
  services/frontend-service/pkg/handler/handle_test.go
  services/frontend-service/pkg/handler/rolloutstatus.go
Labels: minor

#1123 simplify onbording
  Makefile
  README_DEVELOPERS.md
  services/cd-service/Dockerfile
  services/frontend-service/Dockerfile
  services/rollout-service/Dockerfile
Labels: patch

#1124 Fix readyness reporting for the kuberpult event consumer
  services/rollout-service/pkg/versions/versions.go
  services/rollout-service/pkg/versions/versions_test.go
Labels: patch

#1121 SRX-53QJKO: improve longer environment chains
  pkg/api/api.proto
  services/cd-service/pkg/mapper/environments_config.go
  services/cd-service/pkg/mapper/environments_config_test.go
  services/frontend-service/src/assets/_variables.scss
  services/frontend-service/src/ui/components/chip/chip.scss
Labels: patch

#1127 Fix race condition in rollout-service metrics
  services/rollout-service/pkg/cmd/server.go
  services/rollout-service/pkg/metrics/metrics.go
  services/rollout-service/pkg/metrics/metrics_test.go
Labels: patch

#1126 Added missing dependency for make kuberpult
  Makefile
Labels: patch

#1128 Restore original builder image
  infrastructure/docker/builder/Dockerfile
Labels: patch

#1130 Release kuberpult 1.13.0
  CHANGELOG.md
Labels: exclude

#1129 Fix make dependency (again)
  Makefile
  services/frontend-service/Makefile
Labels: exclude

#1133 SRC-K0RM01: improve UX for app and team filters (#1033, #1034)
  services/frontend-service/src/ui/App/index.tsx
  services/frontend-service/src/ui/Pages/Environments/EnvironmentsPage.tsx
  services/frontend-service/src/ui/Pages/Home/Home.tsx
  services/frontend-service/src/ui/Pages/Locks/LocksPage.tsx
  services/frontend-service/src/ui/Pages/ProductVersion/ProductVersionPage.tsx
  services/frontend-service/src/ui/Pages/Releases/ReleasesPage.tsx
  services/frontend-service/src/ui/components/TopAppBar/TopAppBar.tsx
Labels: minor

#1107 Display tags in dropdown
  services/frontend-service/pkg/cmd/server.go
  services/frontend-service/src/ui/components/ProductVersion/ProductVersion.scss
  services/frontend-service/src/ui/components/ProductVersion/ProductVersion.test.tsx
  services/frontend-service/src/ui/components/ProductVersion/ProductVersion.tsx
  services/frontend-service/src/ui/utils/GrpcApi.tsx
  services/frontend-service/src/ui/utils/store.tsx
Labels: minor

#1132 Add missing health tests
  pkg/setup/health_test.go
Labels: patch

#1136 fix(ci): build all services (SRX-8HW1TP)
  .github/workflows/integration-tests.yml
  charts/kuberpult/run-kind.sh
Labels: patch

#1142 fix(i-test): remove fetching main
  .github/workflows/integration-tests.yml
Labels: patch

#1143 Implement waiting in the rollout service
  pkg/api/api.proto
  services/rollout-service/pkg/service/broadcast.go
  services/rollout-service/pkg/service/broadcast_test.go
Labels: minor

#1144 SRX-K0RM01: remove app/teams filter on releases and environments page too
  services/frontend-service/src/ui/Pages/Environments/EnvironmentsPage.tsx
  services/frontend-service/src/ui/Pages/Releases/ReleasesPage.tsx
Labels: patch

#1131 UI: Lock without deploying
  services/frontend-service/src/setupTests.ts
  services/frontend-service/src/ui/components/ReleaseDialog/ReleaseDialog.scss
  services/frontend-service/src/ui/components/ReleaseDialog/ReleaseDialog.tsx
  services/frontend-service/src/ui/components/ReleaseDialog/__snapshots__/ReleaseDialog.test.tsx.snap
  services/frontend-service/src/ui/components/button/ExpandButton.test.tsx
  services/frontend-service/src/ui/components/button/ExpandButton.tsx
  services/frontend-service/src/ui/components/button/button.scss
  services/frontend-service/src/ui/components/dialog/ConfirmationDialog.scss
  services/frontend-service/src/ui/components/dialog/ConfirmationDialog.tsx
  services/frontend-service/src/ui/components/dropdown/dropdown.tsx
Labels: patch

#1146 Add endpoint that returns the version of all services in an environment at a given commit
  pkg/api/api.proto
  services/cd-service/pkg/cmd/server.go
  services/cd-service/pkg/service/tags.go
  services/cd-service/pkg/service/tags_test.go
  services/frontend-service/pkg/cmd/server.go
Labels: minor

#1145 Add waiting to frontend
  charts/kuberpult/templates/frontend-service.yaml
  charts/kuberpult/values.yaml.tpl
  services/frontend-service/pkg/config/config.go
  services/frontend-service/pkg/handler/handle_test.go
  services/frontend-service/pkg/handler/rolloutstatus.go
Labels: minor

#1149 Release 1.14.0
  CHANGELOG.md
Labels: exclude

#1150 fix(release): if a release already exists, return http/409 Conflict (SRX-627DCD)
  services/frontend-service/pkg/handler/release.go
  tests/integration-tests/release_test.go
Labels: patch

#1152 Revert "fix(release): if a release already exists, return http/409 Conflict (SRX-627DCD)"
  services/frontend-service/pkg/handler/release.go
  tests/integration-tests/release_test.go
Labels: patch

#1151 ci(linting): prevent it.only or describe.only usages from being merged (SRX-4Z36FR)
  services/frontend-service/.eslintrc
  services/frontend-service/package.json
Labels: patch

#1164 Enable hot reloading for the UI when starting with earthly
  docker-compose-earthly.yml
Labels: patch

#1135 Force browsers to stop caching index.html
  services/frontend-service/pkg/cmd/server.go
  services/frontend-service/pkg/cmd/server_test.go
  services/frontend-service/public/index.html
  tests/integration-tests/release_test.go
Labels: patch

#1169 Reduce network timeout for local setup
  docker-compose-earthly.yml
  docker-compose.yml
Labels: patch

#1170 Improve local kuberpult run with earthly
  Earthfile
  services/frontend-service/.earthlyignore
  services/frontend-service/Earthfile
Labels: patch

#1167 Run integration tests with Earthly
  .github/workflows/integration-tests.yml
  Earthfile
  Makefile
  tests/integration-tests/cluster-setup/argocd-kuberpult.sh
  tests/integration-tests/cluster-setup/docker-compose-k3s.yml
  tests/integration-tests/cluster-setup/setup-cluster-ssh.sh
Labels: patch

#1159 Kuberpult Page to Display the version of each service for a git tag
  pkg/api/api.proto
  services/cd-service/pkg/service/tags.go
  services/cd-service/pkg/service/tags_test.go
  services/frontend-service/src/setupTests.ts
  services/frontend-service/src/ui/components/ProductVersion/ProductVersion.scss
  services/frontend-service/src/ui/components/ProductVersion/ProductVersion.test.tsx
  services/frontend-service/src/ui/components/ProductVersion/ProductVersion.tsx
  services/frontend-service/src/ui/components/ProductVersion/__snapshots__/ProductVersion.test.tsx.snap
  services/frontend-service/src/ui/utils/store.tsx
Labels: minor

#1180 Fix dropdown to display the selectedTag
  services/frontend-service/src/ui/components/ProductVersion/ProductVersion.test.tsx
  services/frontend-service/src/ui/components/ProductVersion/ProductVersion.tsx
  services/frontend-service/src/ui/components/ProductVersion/__snapshots__/ProductVersion.test.tsx.snap
Labels: bug, minor

#1171 Fixed an NPE in applyArgoEvents
  services/rollout-service/pkg/service/broadcast.go
  services/rollout-service/pkg/service/broadcast_test.go
Labels: patch
