Repository freiheit-com/kuberpult, pull requests merged in 2023-10, with the labels that each got.

#979 Fix: Show "deployed by" also for other versions in ReleaseDialog
  services/frontend-service/src/ui/components/ReleaseDialog/ReleaseDialog.tsx
  services/frontend-service/src/ui/components/ReleaseDialog/__snapshots__/ReleaseDialog.test.tsx.snap
Labels: patch

#971 Refactor ReleaseDialog to not use mui
  services/frontend-service/src/assets/_variables.scss
  services/frontend-service/src/ui/components/ReleaseDialog/ReleaseDialog.scss
  services/frontend-service/src/ui/components/ReleaseDialog/ReleaseDialog.tsx
  services/frontend-service/src/ui/components/ReleaseDialog/__snapshots__/ReleaseDialog.test.tsx.snap
  services/frontend-service/src/ui/components/SideBar/SideBar.tsx
  services/frontend-service/src/ui/components/dialog/ConfirmationDialog.scss
  services/frontend-service/src/ui/components/dialog/ConfirmationDialog.tsx
Labels: patch

#981 Distinguish more rollout states
  pkg/api/api.proto
  services/frontend-service/src/ui/components/ReleaseCard/ReleaseCard.scss
  services/frontend-service/src/ui/components/ReleaseCard/ReleaseCard.tsx
  services/rollout-service/pkg/metrics/metrics.go
  services/rollout-service/pkg/metrics/metrics_test.go
  services/rollout-service/pkg/service/broadcast.go
  services/rollout-service/pkg/service/broadcast_test.go
  services/rollout-service/pkg/versions/versions_test.go
Labels: minor

#982 Release version 1.7.0
  CHANGELOG.md
Labels: exclude

#978 Documentation: Add design principles
  README.md
Labels: patch

#983 Fix: Allow locks for groups with azure enabled
  pkg/auth/azure.go
  pkg/auth/azure_test.go
Labels: patch

#985 Release 1.7.1
  CHANGELOG.md
Labels: exclude

#986 Added Docs for Release Train Recommendations
  ReleaseTrainRecommendations.md
Labels: patch

#988 Fix: ReleaseDialog renders many environments
  services/frontend-service/src/ui/components/ReleaseDialog/ReleaseDialog.scss
Labels: patch

#989 Release 1.7.2
  CHANGELOG.md
Labels: exclude

#990 Add a rest endpoint for obtaining the rollout status of a whole environment group
  infrastructure/scripts/create-testdata/env-group-status.sh
  pkg/api/api.proto
  pkg/auth/azure.go
  pkg/auth/azure_test.go
  services/frontend-service/pkg/cmd/server.go
  services/frontend-service/pkg/handler/handle.go
  services/frontend-service/pkg/handler/handleEnvironments.go
  services/frontend-service/pkg/handler/rolloutstatus.go
  services/frontend-service/src/ui/components/ReleaseCard/ReleaseCard.tsx
  services/rollout-service/pkg/service/broadcast.go
  services/rollout-service/pkg/service/broadcast_test.go
Labels: minor

#994 Fix exec-planner fail on empty stages
  .github/workflows/execution-plan-snippet.yml
Labels: exclude

#993 Release 1.8.0
  CHANGELOG.md
Labels: exclude

#995 Close dialogs on click outside the dialog
  services/frontend-service/src/ui/components/dialog/ConfirmationDialog.tsx
Labels: patch

#1001 Update github.com/ProtonMail/go-crypto digest to afb1ddc
  go.mod
  go.sum
  services/frontend-service/pkg/handler/handle_test.go
Labels: renovate

#1017 Release 1.8.1
  CHANGELOG.md
Labels: exclude

#1020 Change Dex and PgpKeyRing variable name
  charts/kuberpult/templates/cd-service.yaml
  charts/kuberpult/templates/frontend-service.yaml
  pkg/auth/rbac.go
  services/cd-service/pkg/cmd/server.go
  services/frontend-service/pkg/cmd/server.go
  services/frontend-service/pkg/config/config.go
Labels: patch

#1026 Make it easier to run integration tests locally
  charts/kuberpult/run-kind.sh
  tests/integration-tests/.gitignore
  tests/integration-tests/main_test.go
  tests/integration-tests/release_test.go
Labels: patch

#1035 Add an integration test for syncing manifests into the cluster
  tests/integration-tests/rollout_test.go
Labels: minor

#1044 Release 1.9.0
  CHANGELOG.md
Labels: exclude

#1045 Added the first two endpoints for the repository service
  charts/kuberpult/run-kind.sh
  go.mod
  go.sum
  services/cd-service/Makefile
  services/cd-service/pkg/argocd/reposerver/reposerver.go
  services/cd-service/pkg/argocd/reposerver/reposerver_test.go
  services/cd-service/pkg/cmd/server.go
  services/cd-service/pkg/fs/fs.go
  services/cd-service/pkg/grpc/errors.go
  services/cd-service/pkg/interceptors/interceptors.go
Labels: minor

#1047 Release 1.10.0
  CHANGELOG.md
Labels: exclude

#1022 Actually run `go build` in docker (cd&rollout)
  .github/workflows/execution-plan-snippet.yml
  Makefile
  Makefile.variables
  docker-compose.yml
  infrastructure/docker/backend/Dockerfile
  infrastructure/docker/backend/buf_sha256.txt
  infrastructure/docker/backend/start.sh
  infrastructure/docker/builder/Dockerfile
  infrastructure/docker/builder/Makefile
  services/cd-service/Dockerfile
  services/cd-service/Makefile
  services/rollout-service/Dockerfile
  services/rollout-service/Makefile
Labels: patch

#1053 Readme devs: Explain builder image for setup
  README_DEVELOPERS.md
Labels: exclude

#1052 Fix server_test in frontend-service
  services/frontend-service/pkg/cmd/server.go
Labels: patch

#1054 Readme improvement evans
  README_DEVELOPERS.md
Labels: exclude

#1042 Build Go in docker: frontend
  docker-compose.yml
  infrastructure/docker/frontend/Dockerfile
  infrastructure/docker/frontend/buf_sha256.txt
  infrastructure/docker/frontend/start.sh
  services/frontend-service/Dockerfile
  services/frontend-service/Makefile
Labels: patch

#1057 Improve dev Readme for building the builder image
  README_DEVELOPERS.md
Labels: exclude

#1055 Remove "build" image
  README_DEVELOPERS.md
  charts/kuberpult/run-kind.sh
  codereviewr.yaml
  dmake
  docker/build/Dockerfile
  services/cd-service/Makefile
Labels: exclude

#1061 Remove chart testing from CI
  .github/workflows/execution-plan-main.yml
  .github/workflows/execution-plan-pr.yml
  .github/workflows/execution-plan-tag.yml
Labels: exclude

#1062 Deleting empty directories in the manifest repository
  services/cd-service/pkg/repository/repository.go
  services/cd-service/pkg/repository/repository_test.go
  services/cd-service/pkg/repository/transformer.go
  services/cd-service/pkg/repository/transformer_test.go
Labels: patch

#1066 Increase renovates limit from 10 to 25
  renovate.json
Labels: exclude

#1067 Fix docker-compose path to manifest repo
  docker-compose.yml
Labels: exclude

#1069 Fix teams dropdown overflow
  services/frontend-service/src/ui/components/dropdown/dropdown.scss
Labels: patch

#1068 Release 1.10.1
  CHANGELOG.md
Labels: exclude

#1070 Implement include feature of repo server
  services/cd-service/pkg/argocd/reposerver/reposerver.go
  services/cd-service/pkg/argocd/reposerver/reposerver_test.go
Labels: patch

#1071 Release kuberpult 1.10.2
  CHANGELOG.md
Labels: exclude

#1064 Add DEX helm chart to Kuberpult helm chart
  charts/kuberpult/Chart.yaml.tpl
  charts/kuberpult/run-kind.sh
  charts/kuberpult/templates/cd-service.yaml
  charts/kuberpult/templates/frontend-service.yaml
  charts/kuberpult/values.yaml.tpl
Labels: minor
