Repository freiheit-com/kuberpult, pull requests merged in 2023-09, with the labels that each got.

#802 Add rollout service in grpc api
  services/frontend-service/src/ui/App/index.test.tsx
  services/frontend-service/src/ui/App/index.tsx
  services/frontend-service/src/ui/components/ReleaseCard/ReleaseCard.scss
  services/frontend-service/src/ui/components/ReleaseCard/ReleaseCard.test.tsx
  services/frontend-service/src/ui/components/ReleaseCard/ReleaseCard.tsx
  services/frontend-service/src/ui/components/ServiceLane/ServiceLane.tsx
  services/frontend-service/src/ui/utils/GrpcApi.tsx
  services/frontend-service/src/ui/utils/store.test.tsx
  services/frontend-service/src/ui/utils/store.tsx
Labels: minor

#903 Add a feature flag to disable sending webhooks
  charts/kuberpult/templates/cd-service.yaml
  charts/kuberpult/values.yaml.tpl
Labels: minor

#907 Release version 1.1.0
  CHANGELOG.md
Labels: exclude

#909 Write Username instead of email
  pkg/auth/auth.go
Labels: patch

#905 Don't show the rollout status if it's disabled
  services/frontend-service/src/ui/App/index.tsx
  services/frontend-service/src/ui/components/ReleaseCard/ReleaseCard.tsx
  services/frontend-service/src/ui/utils/store.test.tsx
  services/frontend-service/src/ui/utils/store.tsx
Labels: patch

#911 Fix tooltip css format
  services/frontend-service/src/ui/components/tooltip/tooltip.tsx
Labels: patch

#902 Allow locking and unlocking env groups over rest
  docker-compose.yml
  infrastructure/scripts/create-testdata/create-env-group-lock.sh
  infrastructure/scripts/create-testdata/delete-env-group-lock.sh
  pkg/api/api.proto
  pkg/logger/logger.go
  pkg/testutil/testutil.go
  services/cd-service/pkg/repository/repository.go
  services/cd-service/pkg/repository/transformer.go
  services/cd-service/pkg/repository/transformer_test.go
  services/cd-service/pkg/service/batch.go
  services/frontend-service/pkg/cmd/server.go
  services/frontend-service/pkg/handler/handle.go
  services/frontend-service/pkg/handler/handleEnvironments.go
  services/frontend-service/pkg/handler/handle_test.go
  services/frontend-service/pkg/handler/locks.go
  tests/integration-tests/release_test.go
Labels: minor

#912 Release version 1.2.0
  CHANGELOG.md
Labels: exclude

#913 Fix layout in Lock tooltip
  services/frontend-service/src/ui/components/EnvironmentLockDisplay/EnvironmentLockDisplay.tsx
Labels: patch

#910 Notify argocd about updates
  charts/kuberpult/run-kind.sh
  charts/kuberpult/templates/rollout-service.yaml
  charts/kuberpult/values.yaml.tpl
  services/rollout-service/Makefile
  services/rollout-service/pkg/cmd/server.go
  services/rollout-service/pkg/notifier/notifier.go
  services/rollout-service/pkg/notifier/subscriber.go
  services/rollout-service/pkg/notifier/subscriber_test.go
  services/rollout-service/pkg/service/broadcast.go
  services/rollout-service/pkg/service/broadcast_test.go
  services/rollout-service/pkg/service/service.go
  services/rollout-service/pkg/service/service_test.go
  services/rollout-service/pkg/versions/versions.go
  services/rollout-service/pkg/versions/versions_test.go
Labels: minor

#919 Release version 1.3.0
  CHANGELOG.md
Labels: exclude

#917 Added spinner for submitting planned actions
  services/frontend-service/src/ui/Pages/Environments/EnvironmentsPage.tsx
  services/frontend-service/src/ui/Pages/Home/Home.tsx
  services/frontend-service/src/ui/Pages/Locks/LocksPage.tsx
  services/frontend-service/src/ui/Pages/Releases/ReleasesPage.tsx
  services/frontend-service/src/ui/components/SideBar/SideBar.tsx
  services/frontend-service/src/ui/components/Spinner/Spinner.scss
  services/frontend-service/src/ui/components/Spinner/Spinner.tsx
  services/frontend-service/src/ui/components/Spinner/__snapshots__/Spinner.test.tsx.snap
  services/frontend-service/src/ui/utils/AzureAuthProvider.tsx
Labels: patch

#922 Update README.md for users
  README.md
Labels: patch

#924 Submit refreshes to argocd in parallel
  charts/kuberpult/run-kind.sh
  charts/kuberpult/templates/rollout-service.yaml
  charts/kuberpult/values.yaml.tpl
  services/rollout-service/pkg/cmd/server.go
  services/rollout-service/pkg/notifier/notifier.go
  services/rollout-service/pkg/notifier/notifier_test.go
Labels: patch

#921 Added tests for release train to env groups
  services/cd-service/pkg/repository/transformer.go
  services/cd-service/pkg/repository/transformer_test.go
Labels: patch

#925 Explain Helm Parameters in Readme
  README.md
  charts/kuberpult/values.yaml.tpl
Labels: patch

#923 Rollout service: dedup version notifications and notify for app deletions
  services/rollout-service/pkg/versions/versions.go
  services/rollout-service/pkg/versions/versions_test.go
Labels: patch

#927 Release version 1.4.0
  CHANGELOG.md
Labels: exclude

#931 Fix NPE in broadcast.go
  services/rollout-service/pkg/service/broadcast.go
Labels: patch

#928 Change wording for release note generator
  .github_changelog_generator
Labels: patch

#932 Fix README and capitalize some instances of 'kuberpult'
  README.md
Labels: exclude

#933 Actually release version 1.4.0
  CHANGELOG.md
Labels: exclude

#926 User get notified of permission errors on the frontend
  pkg/auth/rbac.go
  pkg/auth/rbac_test.go
  services/cd-service/pkg/repository/transformer.go
  services/cd-service/pkg/repository/transformer_test.go
  services/cd-service/pkg/service/batch_test.go
  services/frontend-service/src/ui/components/SideBar/SideBar.tsx
Labels: minor

#930 Show error about too many items before submit
  services/cd-service/pkg/service/batch.go
  services/frontend-service/src/ui/utils/store.test.tsx
  services/frontend-service/src/ui/utils/store.tsx
Labels: patch

#934 Fix: Show "undeploy version" only in correct circumstances
  services/frontend-service/src/ui/components/ReleaseDialog/ReleaseDialog.tsx
  services/frontend-service/src/ui/components/ReleaseDialog/__snapshots__/ReleaseDialog.test.tsx.snap
Labels: patch

#918 Add Release Version to the frontend
  charts/kuberpult/templates/frontend-service.yaml
  charts/kuberpult/values.yaml.tpl
  pkg/api/api.proto
  services/cd-service/pkg/repository/repository.go
  services/cd-service/pkg/service/overview.go
  services/frontend-service/pkg/cmd/server.go
  services/frontend-service/pkg/config/config.go
  services/frontend-service/pkg/service/config.go
  services/frontend-service/src/ui/components/ReleaseDialog/ReleaseDialog.tsx
  services/frontend-service/src/ui/components/ReleaseDialog/__snapshots__/ReleaseDialog.test.tsx.snap
  services/frontend-service/src/ui/utils/AzureAuthProvider.test.tsx
  services/frontend-service/src/ui/utils/Links.test.tsx
  services/frontend-service/src/ui/utils/Links.tsx
  services/frontend-service/src/ui/utils/__snapshots__/Links.test.tsx.snap
  services/frontend-service/src/ui/utils/store.tsx
Labels: minor

#937 Conditionally show team name in error message
  pkg/auth/rbac.go
  services/cd-service/pkg/repository/transformer_test.go
  services/cd-service/pkg/service/batch_test.go
Labels: minor

#936 Add Release Version to the frontend SideBar
  services/frontend-service/src/ui/components/ReleaseCardMini/ReleaseCardMini.scss
  services/frontend-service/src/ui/components/ReleaseCardMini/ReleaseCardMini.tsx
  services/frontend-service/src/ui/components/SideBar/SideBar.scss
  services/frontend-service/src/ui/components/SideBar/SideBar.tsx
Labels: minor

#939 Release version 1.4.1
  CHANGELOG.md
Labels: exclude

#940 chart: Make the delay to cd service's probes configurable from the values file
  charts/kuberpult/templates/cd-service.yaml
  charts/kuberpult/values.yaml.tpl
Labels: patch

#942 Added default network timeouts for batch service in the frontend service
  services/frontend-service/pkg/cmd/server.go
  services/frontend-service/pkg/service/batch.go
Labels: minor, patch

#941 Add networking timeouts to git pushes
  charts/kuberpult/templates/cd-service.yaml
  charts/kuberpult/values.yaml.tpl
  go.mod
  go.sum
  services/cd-service/pkg/cmd/server.go
  services/cd-service/pkg/grpc/errors.go
  services/cd-service/pkg/repository/repository.go
  services/cd-service/pkg/repository/repository_test.go
  services/cd-service/pkg/repository/testssh/README.md
  services/cd-service/pkg/repository/testssh/server.go
Labels: minor, patch

#944 Release version 1.4.2
  CHANGELOG.md
Labels: exclude

#949 Fix lock symbol size on history page
  services/frontend-service/src/ui/components/ReleaseDialog/ReleaseDialog.scss
Labels: patch

#948 Kill processes earlier when stopping them locally
  docker-compose.yml
Labels: exclude

#947 Shorten commit hashes and use common styling for release versions
  charts/kuberpult/run-kind.sh
  infrastructure/scripts/create-testdata/create-release.sh
  services/frontend-service/src/assets/_components.scss
  services/frontend-service/src/assets/_variables.scss
  services/frontend-service/src/ui/components/ReleaseCard/ReleaseCard.test.tsx
  services/frontend-service/src/ui/components/ReleaseCard/ReleaseCard.tsx
  services/frontend-service/src/ui/components/ReleaseCardMini/ReleaseCardMini.tsx
  services/frontend-service/src/ui/components/ReleaseDialog/ReleaseDialog.scss
  services/frontend-service/src/ui/components/ReleaseDialog/ReleaseDialog.tsx
  services/frontend-service/src/ui/components/ReleaseDialog/__snapshots__/ReleaseDialog.test.tsx.snap
  services/frontend-service/src/ui/components/ReleaseVersion/ReleaseVersion.scss
  services/frontend-service/src/ui/components/ReleaseVersion/ReleaseVersion.tsx
  services/frontend-service/src/ui/components/SideBar/SideBar.tsx
  services/frontend-service/src/ui/utils/Links.test.tsx
  services/frontend-service/src/ui/utils/Links.tsx
  services/frontend-service/src/ui/utils/__snapshots__/Links.test.tsx.snap
  services/frontend-service/src/ui/utils/store.tsx
Labels: minor

#935 Render Link to manifest and source repo
  charts/kuberpult/templates/frontend-service.yaml
  charts/kuberpult/values.yaml.tpl
  pkg/api/api.proto
  services/frontend-service/Makefile
  services/frontend-service/pkg/cmd/server.go
  services/frontend-service/pkg/config/config.go
  services/frontend-service/pkg/service/config.go
  services/frontend-service/src/setupTests.ts
  services/frontend-service/src/ui/components/ReleaseCardMini/ReleaseCardMini.scss
  services/frontend-service/src/ui/components/ReleaseCardMini/ReleaseCardMini.test.tsx
  services/frontend-service/src/ui/components/ReleaseCardMini/ReleaseCardMini.tsx
  services/frontend-service/src/ui/components/ReleaseDialog/ReleaseDialog.scss
  services/frontend-service/src/ui/components/ReleaseDialog/ReleaseDialog.tsx
  services/frontend-service/src/ui/components/ReleaseDialog/__snapshots__/ReleaseDialog.test.tsx.snap
  services/frontend-service/src/ui/components/ReleaseVersion/ReleaseVersion.tsx
  services/frontend-service/src/ui/components/SideBar/SideBar.tsx
  services/frontend-service/src/ui/utils/AzureAuthProvider.test.tsx
  services/frontend-service/src/ui/utils/Links.test.tsx
  services/frontend-service/src/ui/utils/Links.tsx
  services/frontend-service/src/ui/utils/__snapshots__/Links.test.tsx.snap
  services/frontend-service/src/ui/utils/store.tsx
Labels: minor

#955 UI: Show warning before deploying over a lock
  services/frontend-service/src/setupTests.ts
  services/frontend-service/src/ui/components/EnvironmentLockDisplay/EnvironmentLockDisplay.tsx
  services/frontend-service/src/ui/components/ReleaseDialog/ReleaseDialog.scss
  services/frontend-service/src/ui/components/ReleaseDialog/ReleaseDialog.test.tsx
  services/frontend-service/src/ui/components/ReleaseDialog/ReleaseDialog.tsx
  services/frontend-service/src/ui/components/ReleaseDialog/__snapshots__/ReleaseDialog.test.tsx.snap
  services/frontend-service/src/ui/components/ServiceLane/ServiceLane.tsx
  services/frontend-service/src/ui/components/SideBar/SideBar.tsx
  services/frontend-service/src/ui/utils/store.test.tsx
  services/frontend-service/src/ui/utils/store.tsx
Labels: minor

#956 Release 1.5.0
  CHANGELOG.md
Labels: exclude

#957 Changelog improvements
  CHANGELOG.md
Labels: exclude

#958 Readme & Changelog generator improvements
  .github_changelog_generator
  README_DEVELOPERS.md
Labels: exclude

#960 Track DeployTime of applications in the rollout service
  services/rollout-service/pkg/notifier/subscriber.go
  services/rollout-service/pkg/notifier/subscriber_test.go
  services/rollout-service/pkg/service/broadcast.go
  services/rollout-service/pkg/service/broadcast_test.go
  services/rollout-service/pkg/service/service.go
  services/rollout-service/pkg/service/service_test.go
  services/rollout-service/pkg/versions/versions.go
  services/rollout-service/pkg/versions/versions_test.go
Labels: minor

#963 Add environment group name to kuberpult events
  services/rollout-service/pkg/versions/versions.go
  services/rollout-service/pkg/versions/versions_test.go
Labels: patch

#969 Add bash to builder image
  infrastructure/docker/builder/Dockerfile
Labels: exclude

#967 Fix shell invocation for license check
  Makefile
  Makefile.variables
Labels: exclude

#965 testdata: do not include hash in commit message
  infrastructure/scripts/create-testdata/create-release.sh
Labels: exclude

#961 Add metrics to the rollout service
  go.mod
  go.sum
  pkg/metrics/metrics.go
  services/rollout-service/pkg/cmd/server.go
  services/rollout-service/pkg/metrics/metrics.go
  services/rollout-service/pkg/metrics/metrics_test.go
  services/rollout-service/pkg/service/broadcast.go
Labels: minor

#972 Add pod annotations to the rollout pod
  charts/kuberpult/templates/_helpers.tpl
  charts/kuberpult/templates/rollout-service.yaml
  charts/kuberpult/values.yaml.tpl
Labels: minor

#970 Refactor EnvSelection to not use mui
  services/frontend-service/src/ui/components/ServiceLane/EnvSelectionDialog.tsx
  services/frontend-service/src/ui/components/dialog/ConfirmationDialog.tsx
Labels: minor

#973 Release 1.6.0
  CHANGELOG.md
Labels: exclude

#975 Fix: segfault in rollout service
  services/rollout-service/pkg/service/broadcast.go
  services/rollout-service/pkg/service/broadcast_test.go
Labels: patch

#974 Add ingress class name as optional parameter
  charts/kuberpult/templates/ingress.yaml
Labels: minor
