Repository freiheit-com/kuberpult, pull requests merged in 2024-01, with the labels that each got.

#1244 feat: report deployments to datadog
  charts/kuberpult/templates/cd-service.yaml
  charts/kuberpult/values.yaml.tpl
  services/cd-service/pkg/cmd/server.go
  services/cd-service/pkg/repository/repository.go
  services/cd-service/pkg/repository/transformer.go
  services/cd-service/pkg/repository/transformer_test.go
Labels: minor

#1201 feat: validate the manifest is yaml and not changed (SRX-627DCD)
  Earthfile
  go.mod
  go.sum
  pkg/api/api.proto
  services/cd-service/pkg/grpc/errors.go
  services/cd-service/pkg/repository/error.go
  services/cd-service/pkg/repository/repository.go
  services/cd-service/pkg/repository/repository_test.go
  services/cd-service/pkg/repository/testssh/server.go
  services/cd-service/pkg/repository/transformer.go
  services/cd-service/pkg/repository/transformer_test.go
  services/cd-service/pkg/service/batch.go
  services/cd-service/pkg/service/batch_test.go
  services/frontend-service/pkg/handler/release.go
  tests/integration-tests/release_test.go
  tests/integration-tests/rollout_test.go
Labels: patch

#1262 chore: update npm
  services/frontend-service/package.json
  services/frontend-service/pnpm-lock.yaml
Labels: renovate

#1263 chore: update dependency @types/react to v18.2.48
  services/frontend-service/package.json
  services/frontend-service/pnpm-lock.yaml
Labels: renovate

#1278 chore: update dependency sass to ^1.70.0
  services/frontend-service/package.json
  services/frontend-service/pnpm-lock.yaml
Labels: renovate
